[book]
# title = "Compilers: From Source to Machine Code"
title = "Компиляторы: От текста к машинному коду"
authors = ["SamirShef"]
language = "ru"

[output.html]
additional-js = ["theme/pebble-highlight.js"]
